-- PACKAGE   만든김에 삭제랑 수정 procedure 만듦
create or replace NONEDITIONABLE PACKAGE PKG_NBOARD AS 
PROCEDURE PROC_NBOARD_VIEW(
    IN_NB_NUM IN NUMBER,
    O_CUR OUT SYS_REFCURSOR
);
PROCEDURE PROC_NBOARD_DELETE(
    IN_NB_NUM IN NUMBER
);
PROCEDURE PROC_NBOARD_UPDATE(
    IN_NB_NUM IN NUMBER,
    IN_NB_TITLE IN VARCHAR2,
    IN_NB_CONT IN VARCHAR2
);
END PKG_NBOARD;


--BODY
create or replace NONEDITIONABLE PACKAGE BODY PKG_NBOARD AS

  PROCEDURE PROC_NBOARD_VIEW(
    IN_NB_NUM IN NUMBER,
    O_CUR OUT SYS_REFCURSOR
) AS

  BEGIN
  -- 조회수 증가
    UPDATE NOTICE_BOARD SET NB_CNT = NB_CNT + 1
    WHERE NB_NUM = IN_NB_NUM;
    COMMIT;
    
    --NB_NUM으로 조회
    OPEN O_CUR FOR
    SELECT NB_TITLE, NB_CONT, NB_CNT, NB_DATE, M.MEM_NICK, NB_NUM
    FROM NOTICE_BOARD NB, MEMBER M
	WHERE NB_NUM = IN_NB_NUM;

  END PROC_NBOARD_VIEW;


  PROCEDURE PROC_NBOARD_DELETE(
    IN_NB_NUM IN NUMBER
) AS
  BEGIN
    DELETE FROM NOTICE_BOARD WHERE NB_NUM = IN_NB_NUM;
    commit;
  END PROC_NBOARD_DELETE;

  PROCEDURE PROC_NBOARD_UPDATE(
    IN_NB_NUM IN NUMBER,
    IN_NB_TITLE IN VARCHAR2,
    IN_NB_CONT IN VARCHAR2
) AS
  BEGIN
    UPDATE NOTICE_BOARD SET NB_TITLE = IN_NB_TITLE, NB_CONT = IN_NB_CONT,
    NB_DATE = SYSDATE WHERE NB_NUM = IN_NB_NUM;
    commit;
  END PROC_NBOARD_UPDATE;

END PKG_NBOARD;
