--PKG_TRIPREQ
create or replace PACKAGE PKG_TRIPREQ AS 
  --게시물 가져오기
  PROCEDURE PROC_GETBOARD
  ( IN_BOARDNUM IN NUMBER,
    O_CUR       OUT SYS_REFCURSOR);
  --게시물 좋아요
  PROCEDURE PROC_LIKEUPDATE
  ( IN_MEM_NUM IN NUMBER,
    IN_TB_NUM  IN NUMBER,
    LIKECNT    OUT NUMBER
  );
  --게시물 좋아요 취소
   PROCEDURE PROC_LIKEDELETE
  ( IN_MEM_NUM IN NUMBER,
    IN_TB_NUM  IN NUMBER,
    LIKECNT    OUT NUMBER
  );
  --댓글 작성
  PROCEDURE PROC_INSERTCMT
  ( IN_MEM_NUM  IN NUMBER,
    IN_TB_NUM   IN NUMBER,
    IN_TBC_CONT IN VARCHAR2,
    CURRENTPAGE IN NUMBER,
    DPP         IN NUMBER,
    O_CUR       OUT SYS_REFCURSOR
  );
  --댓글 삭제
  PROCEDURE PROC_DELETECMT
  ( IN_TBC_NUM IN NUMBER,
    IN_TB_NUM   IN NUMBER,
    CURRENTPAGE IN NUMBER,
    DPP         IN NUMBER,
    O_CUR       OUT SYS_REFCURSOR
  ) ;
  
END PKG_TRIPREQ;

--PKG_TRIPREQ_BODY
create or replace PACKAGE BODY PKG_TRIPREQ AS
  --게시물 가져오기 조회수+1
  PROCEDURE PROC_GETBOARD
  ( IN_BOARDNUM IN NUMBER,
    O_CUR       OUT SYS_REFCURSOR) AS
  BEGIN
    UPDATE TRIP_BOARD
    SET TB_CNT = TB_CNT+1
    WHERE TB_NUM = IN_BOARDNUM;
    COMMIT;
    
    OPEN O_CUR FOR
   SELECT DISTINCT T.TB_NUM, TB_TITLE, TB_CONT, TB_CNT, TB_DATE, TB_ADDR,
           TB_IMG1, TB_IMG2, TB_IMG3, TB_IMG4, TB_VIDEO1, MEM_NICK,
           (SELECT COUNT(TB_NUM) FROM TB_LIKE WHERE TB_NUM=IN_BOARDNUM ) LIKECNT
           ,(SELECT COUNT(TB_NUM) FROM TB_COMMENT WHERE TB_NUM=IN_BOARDNUM) CMTCNT
    FROM TRIP_BOARD T JOIN MEMBER M ON T.MEM_NUM = M.MEM_NUM
    LEFT JOIN TB_LIKE L ON T.TB_NUM = L.TB_NUM
    LEFT JOIN TB_COMMENT C ON T.TB_NUM = C.TB_NUM
    WHERE T.TB_NUM = IN_BOARDNUM;
  
    COMMIT;

  END PROC_GETBOARD;
  --좋아요 추가, 추천수 반환
  PROCEDURE PROC_LIKEUPDATE
  ( IN_MEM_NUM IN NUMBER,
    IN_TB_NUM  IN NUMBER,
    LIKECNT    OUT NUMBER
  ) AS
  V_TBL_NUM    NUMBER(10,0);
  BEGIN
    SELECT NVL(MAX(TBL_NUM),0)+1
    INTO   V_TBL_NUM
    FROM   TB_LIKE;
  
    INSERT INTO TB_LIKE(TBL_NUM, MEM_NUM, TB_NUM)
    VALUES ( V_TBL_NUM, IN_MEM_NUM, IN_TB_NUM );
    COMMIT;
    
    SELECT COUNT(TB_NUM)
    INTO   LIKECNT
    FROM TB_LIKE
    WHERE TB_NUM = IN_TB_NUM;
    
  END PROC_LIKEUPDATE;
  --게시물 좋아요 취소
  PROCEDURE PROC_LIKEDELETE
  ( IN_MEM_NUM IN NUMBER,
    IN_TB_NUM  IN NUMBER,
    LIKECNT    OUT NUMBER
  ) AS
  BEGIN
    DELETE FROM TB_LIKE
    WHERE TB_NUM  = IN_TB_NUM
    AND   MEM_NUM = IN_MEM_NUM;
    COMMIT;
     
    SELECT COUNT(TB_NUM)
    INTO   LIKECNT
    FROM TB_LIKE
    WHERE TB_NUM = IN_TB_NUM;
    COMMIT;
  END PROC_LIKEDELETE;
  --댓글 작성
  PROCEDURE PROC_INSERTCMT
  ( IN_MEM_NUM  IN NUMBER,
    IN_TB_NUM   IN NUMBER,
    IN_TBC_CONT IN VARCHAR2,
    CURRENTPAGE IN NUMBER,
    DPP         IN NUMBER,
    O_CUR       OUT SYS_REFCURSOR
  ) AS
  V_TBC_NUM     NUMBER(10,0);
  BEGIN
     SELECT NVL(MAX(TBC_NUM),0)+1
     INTO V_TBC_NUM
     FROM TB_COMMENT;
  
     INSERT INTO TB_COMMENT(TBC_NUM, TBC_CONT, MEM_NUM, TB_NUM)
     VALUES      (V_TBC_NUM,IN_TBC_CONT, IN_MEM_NUM, IN_TB_NUM);
     COMMIT;
  
     OPEN O_CUR FOR
     SELECT * FROM
     (SELECT TBC_NUM, TBC_CONT, TBC_DATE, MEM_NICK , ROW_NUMBER() OVER (ORDER BY TBC_NUM DESC NULLS LAST) RN
     FROM   TB_COMMENT C JOIN TRIP_BOARD T ON C.TB_NUM = T.TB_NUM
     JOIN MEMBER M ON C.MEM_NUM = M.MEM_NUM
     AND C.TB_NUM = IN_TB_NUM)T
     WHERE RN BETWEEN 1+(10)*(CURRENTPAGE+DPP) AND 10+(10)*(CURRENTPAGE+DPP);
  END PROC_INSERTCMT;
   --댓글 삭제
  PROCEDURE PROC_DELETECMT
  ( IN_TBC_NUM IN NUMBER,
    IN_TB_NUM   IN NUMBER,
    CURRENTPAGE IN NUMBER,
    DPP         IN NUMBER,
    O_CUR       OUT SYS_REFCURSOR
  ) AS
  BEGIN
     DELETE FROM TB_COMMENT
	 WHERE TBC_NUM = IN_TBC_NUM;
	 COMMIT;
    
     OPEN O_CUR FOR
     SELECT * FROM
     (SELECT TBC_NUM, TBC_CONT, TBC_DATE, MEM_NICK , ROW_NUMBER() OVER (ORDER BY TBC_NUM DESC NULLS LAST) RN
     FROM   TB_COMMENT C JOIN TRIP_BOARD T ON C.TB_NUM = T.TB_NUM
     JOIN MEMBER M ON C.MEM_NUM = M.MEM_NUM
     AND C.TB_NUM = IN_TB_NUM)T
     WHERE RN BETWEEN 1+(10)*(CURRENTPAGE+DPP) AND 10+(10)*(CURRENTPAGE+DPP);
  END PROC_DELETECMT;

END PKG_TRIPREQ;
