-- 멤버 테이블
CREATE TABLE MEMBER (
MEM_NUM NUMBER(10,0) PRIMARY KEY,
MEM_LEVEL NUMBER(3,0) DEFAULT 0,
MEM_NAME VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(30) NOT NULL UNIQUE,
MEM_PWD VARCHAR2(30) NOT NULL,
MEM_GENDER VARCHAR2(3) NOT NULL,
MEM_ADDR VARCHAR2(200) NOT NULL,
MEM_TEL VARCHAR2(20),
MEM_BIRTH VARCHAR2(20) NOT NULL,
MEM_NICK VARCHAR2(30) NOT NULL UNIQUE,
MEM_EMAIL VARCHAR2(100)
);

--여행지 추천게시판
CREATE TABLE TRIP_BOARD(
TB_NUM NUMBER(10,0) PRIMARY KEY,
TB_TITLE VARCHAR2(100) NOT NULL,
TB_CONT VARCHAR2(4000) NOT NULL,
TB_CNT NUMBER(10,0) DEFAULT 0,
TB_DATE DATE DEFAULT SYSDATE,
TB_ADDR VARCHAR2(100) NOT NULL,
TB_IMG1 VARCHAR2(200),
TB_IMG2 VARCHAR2(200),
TB_IMG3 VARCHAR2(200),
TB_IMG4 VARCHAR2(200),
TB_VIDEO1 VARCHAR2(300),
TB_VIDEO2 VARCHAR2(300),
MEM_NUM NUMBER(10,0) ,
CONSTRAINT FK_MEM_NUM FOREIGN  KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);

--자유게시판
CREATE TABLE FREE_BOARD(
FB_NUM NUMBER(10,0) PRIMARY KEY,
FB_TITLE VARCHAR2(100) NOT NULL,
FB_CONT VARCHAR2(4000) NOT NULL,
FB_CNT NUMBER(10,0) DEFAULT 0,
FB_DATE DATE DEFAULT SYSDATE,
FB_IMG1 VARCHAR2(200),
FB_IMG2 VARCHAR2(200),
FB_IMG3 VARCHAR2(200),
FB_IMG4 VARCHAR2(200),
FB_VIDEO1 VARCHAR2(300),
FB_VIDEO2 VARCHAR2(300),
MEM_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_FREE_NUM FOREIGN  KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);


--공지사항
CREATE TABLE NOTICE_BOARD(
NB_NUM NUMBER(10,0) PRIMARY KEY,
NB_TITLE VARCHAR2(100) NOT NULL,
NB_CONT VARCHAR2(4000) NOT NULL,
NB_CNT NUMBER(10,0) DEFAULT 0,
NB_DATE DATE DEFAULT SYSDATE,
NB_IMG VARCHAR2(200),
NB_VIDEO VARCHAR2(300),
MEM_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_NOTICE_NUM FOREIGN  KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);


--여행지 추천 게시판의 댓글
CREATE TABLE TB_COMMENT(
TBC_NUM NUMBER(10,0) PRIMARY KEY,
TBC_CONT VARCHAR2(300) NOT NULL,
TBC_DATE DATE DEFAULT SYSDATE,
MEM_NUM NUMBER(10,0),
TB_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_TB_NUM FOREIGN  KEY (TB_NUM) REFERENCES TRIP_BOARD(TB_NUM)
);


--자유게시판의 댓글
CREATE TABLE FB_COMMENT(
FBC_NUM NUMBER(10,0) PRIMARY KEY,
FBC_CONT VARCHAR2(300) NOT NULL,
FBC_DATE DATE DEFAULT SYSDATE,
MEM_NUM NUMBER(10,0),
FB_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_FB_NUM FOREIGN  KEY (FB_NUM) REFERENCES FREE_BOARD(FB_NUM)
);


--신고 테이블
CREATE TABLE REPORT(
REPORT_NUM NUMBER(10,0) PRIMARY KEY,
REPORT_CONT VARCHAR2(300) NOT NULL,
REPORT_DATE DATE DEFAULT SYSDATE,
REPORT_MEM NUMBER(10,0) NOT NULL, -- 신고 한 사람
REPORTED_MEM NUMBER(10,0) NOT NULL, -- 신고 당한 사람
CONSTRAINT FK_REPORT_MEM_NUM FOREIGN  KEY (REPORT_MEM) REFERENCES MEMBER(MEM_NUM),
CONSTRAINT FK_REPORTED_MEM_NUM FOREIGN  KEY (REPORTED_MEM) REFERENCES MEMBER(MEM_NUM)
);

-- 여행 게시판 좋아요
CREATE TABLE TB_LIKE(
TBL_NUM NUMBER(10,0) PRIMARY KEY,
TBL_DATE DATE DEFAULT SYSDATE,
MEM_NUM NUMBER(10,0),
TB_NUM NUMBER(10,0),
CONSTRAINT FK_TB_NUM1 FOREIGN  KEY (TB_NUM) REFERENCES TRIP_BOARD(TB_NUM)
);

-- 자유게시판 좋아요
CREATE TABLE FB_LIKE(
FBL_NUM NUMBER(10,0) PRIMARY KEY,
FBL_DATE DATE DEFAULT SYSDATE,
MEM_NUM NUMBER(10,0),
FB_NUM NUMBER(10,0),
CONSTRAINT FK_FB_NUM1 FOREIGN  KEY (FB_NUM) REFERENCES FREE_BOARD(FB_NUM)
);

-- 여행게시판 댓글 좋아요
CREATE TABLE TBC_LIKE(
TBCL_NUM NUMBER(10,0) PRIMARY KEY,
TBCL_DATE DATE DEFAULT SYSDATE,
MEM_NUM NUMBER(10,0),
TBC_NUM NUMBER(10,0),
CONSTRAINT FK_TBC_NUM FOREIGN  KEY (TBC_NUM) REFERENCES TB_COMMENT(TBC_NUM)
);

--자유게시판 댓글 좋아요
CREATE TABLE FBC_LIKE(
FBCL_NUM NUMBER(10,0) PRIMARY KEY,
FBCL_DATE DATE DEFAULT SYSDATE,
MEM_NUM NUMBER(10,0),
FBC_NUM NUMBER(10,0),
CONSTRAINT FK_FBC_NUM FOREIGN  KEY (FBC_NUM) REFERENCES FB_COMMENT(FBC_NUM)
);
